### ISSUE TITLE
Nonsense for any action 

### ISSUE THREAD

**Issue by werasik2aa** [Aelto/tw3-shared-utils#16]
public function setOffset(value: Vector): SU_Oneliner {
    this.offset = offset;
    return this;
  }

  The Misstake ? This should be

 public function setOffset(value: Vector): SU_Oneliner {
    this.offset = value;
    return this;
  }

SCRIPT: oneliner.ws

**Comment by Aelto** [comment]
Good find ! But what's up with the name of the issue?

**Comment by werasik2aa** [comment]
i don't know any words to explain. I just write the title of the issue by what first came to my mind.
